[tool.poetry]
name = "image_text"
version = "0.1.0"
description = "Place text to image"
authors = ["German"]

[tool.poetry.dependencies]
python = "^3.12"
pillow = "^10.3.0"
quote-client = { path = "../quote_client"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
