version: "3.9"

x-env:
  &default-env
  env_file: env/.env

services:
  telegram_bot:
    <<: *default-env
    build:
      context: .
      dockerfile: ci-cd/bot.Dockerfile
    depends_on:
      - pg
    networks:
      - webapp-access
      - db-access

  pg:
    <<: *default-env
    command: -c 'fsync=off' -c 'full_page_writes=off'
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"
    networks:
      - db-access
      - minio-network

  webapp:
    <<: *default-env
    build:
      context: .
      dockerfile: ci-cd/webapp.Dockerfile
    volumes:
      - ./src/webapp/:/app/webapp/
    ports:
      - 8000:8000
    depends_on:
      - pg
    networks:
      - webapp-access
      - db-access
      - minio-network
  
  minio:
    <<: *default-env
    build:
      context: .
      dockerfile: ci-cd/minio.Dockerfile
    volumes:
      - ./minio_data/data/:/data
      - ./minio_data/conf/:/root/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio-network


volumes:
  postgres_data:

networks:
  db-access:
  webapp-access:
  minio-network:
