[tool.poetry]
name = "quotebot"
version = "0.1.0"
description = "bot for managing posts in telegram"
authors = ["Simon Druchinin, Prosyannikov German"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.5.0"
python-dotenv = "^1.0.1"
fastapi = "^0.110.3"
uvicorn = {extras = ["standard"], version = "^0.29.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
