[tool.poetry]
name = "quotebot"
version = "0.1.0"
description = "app for managing posts in telegram"
authors = ["Simon Druchinin, Prosyannikov German"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
