"""Initial

Revision ID: 23a493d90a96
Revises: 
Create Date: 2024-05-01 04:31:18.745848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '23a493d90a96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('image_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('image_with_text_url', sqlalchemy_file.types.FileField(), nullable=True),
    sa.Column('keyword_ru', sa.String(length=64), nullable=False),
    sa.Column('keyword_en', sa.String(length=64), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes_posts')
    # ### end Alembic commands ###
