"""Added multiple image and image tables

Revision ID: a5aa3e105fd0
Revises: abe7995ea6f3
Create Date: 2024-07-18 13:30:49.099009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'a5aa3e105fd0'
down_revision: Union[str, None] = 'abe7995ea6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes_posts_multiple_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('post_multiple_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_multiple_image_id'], ['quotes_posts_multiple_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes_images')
    op.drop_table('quotes_posts_multiple_images')
    # ### end Alembic commands ###
