[tool.poetry]
name = "jay_copilot_client"
version = "0.1.0"
description = ""
authors = ["Druchinin Simon"]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
pydantic = "^2.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
