[tool.poetry]
name = "image_text_client"
version = "0.1.0"
description = "Place text to image"
authors = ["Simon Druchinin"]

[tool.poetry.dependencies]
python = "^3.12"
pillow = "^10.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
