name: Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy poetry
        pip install poetry
        poetry install
    - name: Analysing the code
      run: |
        ruff format --check
        ruff check
        mypy $(git ls-files '*.py')
  check_mypy:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.12"]
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy poetry
          pip install poetry
          poetry install
      - name: Analysing the code
        run: |
          mypy $(git ls-files '*.py')
